pipeline{
    agent any
    tools{
        nodejs 'nodejs'
    }
    stages {
        stage('Workspace Cleaning'){
            steps{
                cleanWs()
            }
        }
        stage('Checkout from Git'){
            steps{
                git branch: 'master', url: 'https://github.com/AmanPathak-DevOps/Netflix-Clone-K8S-End-to-End-Project.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                dir('Application-Code') {
                    // Install project dependencies (needed for OWASP + build)
                    sh 'npm install'
                }
            }
        }
        stage("Docker Image Build"){
            steps{
                dir('Application-Code') {
                    script{
                       withDockerRegistry(credentialsId: 'docker', toolName: 'docker'){   
                           
                           withCredentials([string(credentialsId: 'tmdb-api', variable: 'TMDB_API_KEY')]) {
                                sh """
                                    docker build \
                                    --build-arg TMDB_V3_API_KEY=${TMDB_API_KEY} \
                                    -t netflix .
                                """
                            }
                        }
                    }
                }
            }
        }
        stage("Docker Image Pushing"){
            steps{
                dir('Application-Code') {
                    script{
                       withDockerRegistry(credentialsId: 'docker', toolName: 'docker'){   
                           sh "docker tag netflix avian19/netflix:latest "
                           sh "docker push avian19/netflix:latest "
                        }
                    }
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                script {
                    dir('Kubernetes') {
                        withKubeConfig(credentialsId: 'k8s') {
                            sh 'kubectl apply -f deployment.yml'
                            sh 'kubectl apply -f service.yml'
                            sh 'kubectl get svc'
                            sh 'kubectl get all'
                        }
                    }
                }
            }
        }
    }
}
